export const data = [
  {
    id: "ISS-001",
    issue: "Dashboard charts fail on slow connection",
    status: "Closed",
    priority: "High",
    severity: "Moderate",
    assignee: { name: "Taylor Brooks", initials: "TB" },
    activity: 5,
    created: "2026-01-16",
  },
  {
    id: "ISS-002",
    issue: "Pagination resets unexpectedly on filter",
    status: "In Progress",
    priority: "Medium",
    severity: "Minor",
    assignee: { name: "Jamie Chen", initials: "JC" },
    activity: 2,
    created: "2026-01-17",
  },
  {
    id: "ISS-003",
    issue: "CSV export missing assignee column",
    status: "Resolved",
    priority: "Low",
    severity: "Minor",
    assignee: { name: "Taylor Brooks", initials: "TB" },
    activity: 3,
    created: "2024-01-18",
  },
  {
    id: "ISS-004",
    issue: "Memory leak in WebSocket connection",
    status: "In Progress",
    priority: "Critical",
    severity: "Critical",
    assignee: { name: "Sam Rivera", initials: "SR" },
    activity: 1,
    created: "2026-01-19",
  },
  {
    id: "ISS-005",
    issue: "Date picker shows wrong timezone",
    status: "Open",
    priority: "High",
    severity: "Major",
    assignee: { name: "Jamie Chen", initials: "JC" },
    activity: 1,
    created: "2024-01-20",
  },
  {
    id: "ISS-003",
    issue: "CSV export missing assignee column",
    status: "Resolved",
    priority: "Low",
    severity: "Minor",
    assignee: { name: "Taylor Brooks", initials: "TB" },
    activity: 3,
    created: "2026-01-18",
  },
  {
    id: "ISS-004",
    issue: "Memory leak in WebSocket connection",
    status: "In Progress",
    priority: "Critical",
    severity: "Critical",
    assignee: { name: "Sam Rivera", initials: "SR" },
    activity: 1,
    created: "2026-01-19",
  },
  {
    id: "ISS-005",
    issue: "Date picker shows wrong timezone",
    status: "Open",
    priority: "High",
    severity: "Major",
    assignee: { name: "Jamie Chen", initials: "JC" },
    activity: 1,
    created: "2026-01-20",
  },
];